name: CD

on:
  release:
    types: [created]

jobs:
  ci:
    uses: paulocoelho098/EasyResults.WebExtensions/.github/workflows/ci.yml@main

  on-success:
    runs-on: windows-latest
    needs: [ci]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: EasyResults.WebExtensions/bin/Release/net7.0

      - name: Pack NuGet package
        run: dotnet pack --configuration Release

      - name: Publish NuGet package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push **/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
